### ISSUE TITLE
GitHub API rate limits for downloading latest Gitleaks tool

### ISSUE THREAD

**Issue by babicahmed** [JoostVoskuil/azure-devops-gitleaks#51]
Hi,

When running gitleaks for a larger scope, I get a limitation error. Please let me know how to proceed or fix this.

##[error]API rate limit exceeded for xxxxxxxxxxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

**Comment by JoostVoskuil** [comment]
Hi @babicahmed ,

The task only does 1 API call per run to fetch the build changes or the commits beloning to a PR. Are you sure that this is because of the Gitleaks task? Seems unlikely to me.

Can you elaborate what 'larger scope' means?

With regards,

Joost

**Comment by JoostVoskuil** [comment]
Hi @babicahmed any updates on this?

**Comment by JoostVoskuil** [comment]
I will look at this. This seems to be the GitHub API rate limits

**Comment by JoostVoskuil** [comment]
Hard to cope. The task does now a three time retry. You can also specify the version of the GitLeaks tool hardcoded. I've updated the documentation

**Comment by ctoestreich** [comment]
@JoostVoskuil we hit this error quite frequently in Adao where we see rate limit cut offs.  It would appear people may be getting hit by the anonymous 60/Hr limit downloading the release.  Is there a reason to use the api and not just an http link to the release to avoid the api rate limits?  Or Perhaps hosting releases in public artifact storage or elsewhere to download instead of calling api?

https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#:~:text=For%20unauthenticated%20requests%2C%20the%20rate,not%20the%20person%20making%20requests.

**Comment by ctoestreich** [comment]
The url for download has no rate limits; ie https://github.com/JoostVoskuil/gitleaks/archive/refs/tags/v8.16.0.zip

**Comment by JoostVoskuil** [comment]
Hi @ctoestreich , the API call is required to get the latest release of Gitleaks. If you specify the version of Gitleaks then the API call does not happen.

If you know a way to retrieve the latest version of the Gitleaks tool without the GitHub API call I can fix this, however, I don't see a way to do this otherwise.

**Comment by jessehouwing** [comment]
> Hi @ctoestreich , the API call is required to get the latest release of Gitleaks. If you specify the version of Gitleaks then the API call does not happen.
> 
> If you know a way to retrieve the latest version of the Gitleaks tool without the GitHub API call I can fix this, however, I don't see a way to do this otherwise. 

Try replacing the version with `latest`.

Like so:

`https://github.com/jessehouwing/azure-pipelines-tasks-zips/releases/latest/download/AzureAppServiceManage-sxs.cd48cada-0dd0-53ab-a3f9-eedd0c97e4f6-0.223.0.zip`

**Comment by JoostVoskuil** [comment]
Hi @jessehouwing Thanx for your suggestion. I know, two things there: 

1) I still need the version number to cache Gitleaks tool inside the pipeline agent tool cache. No idea to get the version number with the latest tag. 
2) The Gitleaks binaries also contain a version number (https://github.com/gitleaks/gitleaks/releases/download/v8.16.4/gitleaks_8.16.4_linux_x64.tar.gz)

I guess if you solve either one of the two points you can solve the other one haha
Any ideas?

**Comment by jessehouwing** [comment]
Urgh. Yeah my trick would be to replicate the binaries to another release
and get rid of the variance. Free GitHub storage tow the win...

Just running a daily GitHub actions workflow to see if there's a new
release.

Not having the version in the filename has its uses.

**Comment by JoostVoskuil** [comment]
I think this isn't worth the hassle. It actually happens only when running on Hosted agents or big organisations with a high volume of agents (I think even VMSS with recycle on).

Workaround is to specify the version number in the Gitleaks task. If someone wants to create a solution for this I am happy to approve a PR.

**Comment by JoostVoskuil** [comment]
This issue is solved in the latest version of the task. The task gets the version in a different way
