### ISSUE TITLE
Click through not working like sarif file generated from credscan

### ISSUE THREAD

**Issue by VincentOspazi** [JoostVoskuil/azure-devops-gitleaks#52]
when viewing the results in the scans tab( extension [SARIF SAST Scans Tab](https://marketplace.visualstudio.com/items?itemName=sariftools.scans)) using the almost depricated credscan, I can click on the error line and it brings me to the specified line inside the repo.

Can this feature also be implemented in gitleaks?  I saw the format was a little bit different, maybe this is the reason?

**Comment by JoostVoskuil** [comment]
Hi @VincentOspazi ,

I like the idea, however I don't think this is possible. The report generation is part of GitLeaks itself and not part of this extension. The only think that this extension does is upload the report to a valid location in Azure DevOps so that the SARIF SAST Scans Tab can pick this up. Basically it's pretty dumb ;)

Making your suggestion work requires that Zachary needs to include the correct URL with  line of code to the web based source control repository.  I think this approach is different depending on the tool. Maybe you can make a suggestion here: https://github.com/zricethezav/gitleaks but again, this is something I cannot control. Sorry for that.
